#exclude: ['.github', 'Gemfile', 'Gemfile.lock', 'techstack.yml', 'github.md', 'techstack.md', 'LICENSE'] 

#plugins:
#  - jekyll-analytics

#jekyll_analytics:
#  Plausible:
#    domain: 'docs.noclocks.dev'
#    source: 'https://plausible.io/js/script.js'
